# Generated by Django 6.1.1 on 2026-09-09 00:01

import apps.catalog.models
import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CourseRatingSummary",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avg_difficulty", models.FloatField(blank=True, null=True)),
                ("avg_workload", models.FloatField(blank=True, null=True)),
                ("avg_usefulness", models.FloatField(blank=True, null=True)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProfessorRatingSummary",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("avg_clarity", models.FloatField(blank=True, null=True)),
                ("avg_helpfulness", models.FloatField(blank=True, null=True)),
                ("avg_fairness", models.FloatField(blank=True, null=True)),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "abstract": False,
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Catalog code, e.g. CSC 240.", max_length=16
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("credits", models.PositiveSmallIntegerField(default=3)),
                ("department", models.CharField(max_length=64)),
                (
                    "prereq_text",
                    models.TextField(
                        blank=True, help_text="Free text, as the catalog prints it."
                    ),
                ),
                (
                    "professor_ids",
                    django_mongodb_backend.fields.ArrayField(
                        base_field=django_mongodb_backend.fields.ObjectIdField(),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "rating_summary",
                    django_mongodb_backend.fields.EmbeddedModelField(
                        default=apps.catalog.models.CourseRatingSummary,
                        embedded_model="catalog.courseratingsummary",
                    ),
                ),
            ],
            options={
                "ordering": ["code"],
                "indexes": [
                    models.Index(fields=["department"], name="catalog_course_dept_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("code",), name="catalog_course_code_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=64)),
                ("last_name", models.CharField(max_length=64)),
                ("department", models.CharField(max_length=64)),
                (
                    "title",
                    models.CharField(
                        blank=True, help_text="e.g. Associate Professor.", max_length=64
                    ),
                ),
                ("photo", models.URLField(blank=True)),
                ("bio", models.TextField(blank=True)),
                (
                    "course_ids",
                    django_mongodb_backend.fields.ArrayField(
                        base_field=django_mongodb_backend.fields.ObjectIdField(),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "rating_summary",
                    django_mongodb_backend.fields.EmbeddedModelField(
                        default=apps.catalog.models.ProfessorRatingSummary,
                        embedded_model="catalog.professorratingsummary",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
                "indexes": [
                    models.Index(fields=["department"], name="catalog_prof_dept_idx"),
                    models.Index(
                        fields=["last_name", "first_name"], name="catalog_prof_name_idx"
                    ),
                ],
            },
        ),
    ]
