# Generated by Django 6.1.1 on 2026-09-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="professorratingsummary",
            name="avg_overall",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
