# Generated by Django 6.1.1 on 2026-09-10 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_professor_directory_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="catalog_year",
            field=models.CharField(
                blank=True, help_text="e.g. 2025-2026.", max_length=16
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="coreq_text",
            field=models.TextField(
                blank=True, help_text="Free text, as the catalog prints it."
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="subject",
            field=models.CharField(
                blank=True, help_text="Code prefix, e.g. CSC.", max_length=8
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="credits",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="department",
            field=models.CharField(max_length=120),
        ),
    ]
