# Generated by Django 6.1.1 on 2026-09-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_course_catalog_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="professor",
            name="rmp_avg_difficulty",
            field=models.FloatField(
                blank=True, help_text="RMP difficulty, 1-5.", null=True
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="rmp_avg_rating",
            field=models.FloatField(
                blank=True, help_text="RMP quality, 1-5.", null=True
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="rmp_legacy_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="RMP's stable professor id; enables a direct link.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="rmp_num_ratings",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="professor",
            name="rmp_retrieved",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professor",
            name="rmp_would_take_again_pct",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="professorratingsummary",
            name="source",
            field=models.CharField(
                blank=True,
                choices=[("ramhub", "Students on RamHub"), ("rmp", "RateMyProfessors")],
                max_length=16,
            ),
        ),
    ]
