# Generated by Django 6.1.1 on 2026-09-10 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_rmp_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="professorratingsummary",
            name="rank_score",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
